image: python:latest

pages:
  script:
    - pip install -r requirements.txt
    - cd docs
    - pip install -r requirements.txt
    - make html
    - mv build/html ../public
  artifacts:
    paths:
      - public
  only:
    - develop
    - master
