image: "python:3.7"

stages:
  - setup
  - deploy

setup:
  stage: setup
  script:
    - pip3 install -r requirement.txt
    - ./bootstrap
  only:
    - develop
    - master


pages:
  stage: deploy
  script:
    - cd docs
    - pip3 install -r requirement.txt
    - make html
    - mv build/html ../public
  artifacts:
    paths:
      - public
  only:
    - develop
    - master

testsuite:
  stage: deploy
  script:
    - python src/asthook.py --help
  only:
    - develop
    - master
