image: "debian:buster"

stages:
  - deploy


before_script:
  - apt-get update -qq
  - apt install -y -qq python3 python3-pip wget git
  - pip3 install -r requirement.txt


pages:
  stage: deploy
  script:
    - cd docs
    - pip3 install -r requirement.txt
    - make html
    - mv build/html ../public
  artifacts:
    paths:
      - public
  only:
    - master

testsuite:
  stage: deploy
  script:
    - ./bootstrap.sh
    - python3 src/asthook.py --help
  only:
    - master
