image: python:latest

pages:
  script:
    - pip install -r docs/requirements.txt
    - cd docs/ && make html
    - mv build/html public
  artifacts:
    paths:
      - public
  only:
    - develop
    - master
