static:
  - tree: true
  - tree_path: "/com/example"
    #  - tree_path: "/"

  - gen_hook:
    - "TraceEvents.nativeDisableProviders"
      #  - list_funcs: 
      #    - '^.*'
      #    - '^.*'
      #  - list_funcs_call: 
      #    - '^.*'
      #    - '^.*'

#### Intent give data when it's call ####
#  - list_funcs_call:
#    - '.*'
#    - 'setResult'

#### Application send broadcast ####
#  - list_funcs_call:
#    - '.*'
#    - 'sendBroadcast'
  - test: false
  - test: false
  
dynamic:
  - sdktools: "/usr/lib/android-sdk"
  - phone: "Pixel_3a_XL_API_22"
    #  - proxy: "127.0.0.1:8080"
  - proxy_cert: "misc/burp.der"

  - sslpining: false


