static:
  - tree: true
  - tree_path: "/com"

  - gen_hook: "LoginViewModel.isUserNameValid"
  - list_funcs: 
    - '^Login.*'
    - '^.*'
  
dynamic:
# - emulator: "/usr/lib/android-sdk"
# - phone: "Pixel_3a_XL_API_22"
  - proxy: "127.0.0.1:8080"
  - proxy_cert: "misc/burp.der"

  - test: false
  - sslpining: true


