static:
  #- tree: true
  #- tree_path: "/com"

  #- gen_hook:
  #  - "TraceEvents.nativeDisableProviders"
  #- list_funcs: 
  #  - '^Login.*'
  #  - '^.*'
  #- test: false
  
dynamic:
  - sdktools: "/usr/lib/android-sdk"
  - phone: "phone_audit2"
  - proxy: "127.0.0.1:8080"
  - proxy_cert: "misc/burp.der"

  - sslpinning: true


