static:
  - tree: false
  - verbose: "info"
  - tree_path: "/"
    #  - tree_path: "/"

  - gen_hook:
    - "TraceEvents.nativeDisableProviders"
  - list_funcs: 
    - '^.*'
    - '^.*'
      #  - list_funcs_call: 
      #    - '^.*'
      #    - '^.*'

#### Intent give data when it's call ####
#  - list_funcs_call:
#    - '.*'
#    - 'setResult'

#### Application send broadcast ####
#  - list_funcs_call:
#    - '.*'
#    - 'sendBroadcast'

#### Find Webview with js added ####
#  - list_funcs_call:
#    - '.*'
#    - 'addJavascriptInterface|WebView.*'
#    TODO: this.getSupportFragmentManager().a("WebviewFragment")

#### Find PendingIntent ####
# If itent is not specified the data is broadcast
# https://www.cs.uni-potsdam.de/se/papers/esorics18.pdf
#  - list_funcs_call:
#    - '^PendingIntent$'
#    - '^getActivity$'
  - test: false
  
dynamic:
  - sdktools: "/usr/lib/android-sdk"
    #  - phone: "phone_audit2"
    #  - proxy: "127.0.0.1:8080"
    #  - proxy_cert: "misc/burp.der"

  - sslpinning: true


